### ISSUE TITLE
FT/NFT: make a research about them

### ISSUE THREAD

**Issue by telezhnaya** [near/near-indexer-for-explorer#108]
It would be cool to show the corresponding information about them. 
As the beginning, we need to dig into the subject more

https://nomicon.io/Standards/README.html

**Comment by zcstarr** [comment]
Going to just drop a comment here as well , that we have this new standard we're working to land that's a multi token standard in the vein of erc-1155. https://github.com/near/NEPs/pull/245 . Just something to consider for the explorer as well, once it lands.

**Comment by telezhnaya** [comment]
@zcstarr thank you!

**Comment by telezhnaya** [comment]
We successfully added the NFT standard near/NEPs#256
We added the support of NFT events in Indexer #169 
We started to think about FT standard near/NEPs#271
Looks like we are on the right track!
