### ISSUE TITLE
Transactions with NULL-byte in method names of ADD_KEY actions with FUNCTION_CALL permissions cannot be stored in the DB

### ISSUE THREAD

**Issue by frol** [near/near-indexer-for-explorer#109]
```
May 21 10:08:37.015 ERROR indexer_for_explorer: Error occurred while TransactionAction were adding to database. Retrying in 204800 milliseconds...
 Execute(
    DatabaseError(
        __Unknown,
        "unsupported Unicode escape sequence",
    ),
)
[
    TransactionAction {
        transaction_hash: "CzMLKch1oV4GLTFEVkpWR1hwTAm2otCsvjgfXBNo6hmN",
        index_in_transaction: 0,
        action_kind: AddKey,
        args: Object({
            "public_key": String(
                "ed25519:4BGbi2xFEp7hBsfGGLsrzB2DY2VTaADxh4KdpqdCsgSf",
            ),
            "access_key": Object({
                "nonce": Number(
                    0,
                ),
                "permission": Object({
                    "permission_kind": String(
                        "FUNCTION_CALL",
                    ),
                    "permission_details": Object({
                        "allowance": Null,
                        "receiver_id": String(
                            "lockup.near",
                        ),
                        "method_names": Array([
                            String(
                                "\u{0}\u{0}\u{0}",
                            ),
                        ]),
                    }),
                }),
            }),
        }),
    },
]
```

We should do something about these transactions. NULL-byte strings are not supported by PostgreSQL.

**Comment by khorolets** [comment]
I recall we met this during the development it was resolved somehow. I'll look into code to update the conversation.

**Comment by khorolets** [comment]
Despite I recall we had some way to handle it, indexer has failed on node3 while running from genesis.

**Comment by khorolets** [comment]
@frol here's what we are doing to handle it. https://github.com/near/near-indexer-for-explorer/blob/master/src/models/serializers.rs#L85 And it seemed to be helping, but stopped. Any thoughts?

**Comment by frol** [comment]
@khorolets the code you referenced covers the `method_name` of the `FUNCTION_CALL` action, but the transaction in question has the `method_names` parameter inside the `FUNCTION_CALL` permissions inside `ADD_KEY` action.

**Comment by khorolets** [comment]
> @khorolets the code you referenced covers the `method_name` of the `FUNCTION_CALL` action, but the transaction in question has the `method_names` parameter inside the `FUNCTION_CALL` permissions inside `ADD_KEY` action.

Great catch, thanks! What do you suggest?

**Comment by frol** [comment]
No good ideas so far, I fear we will have to manually serialize that structure as well :disappointed:
