### ISSUE TITLE
Ensure --store-genesis works after optimization on nearcore side

### ISSUE THREAD

**Issue by khorolets** [near/near-indexer-for-explorer#117]
nearcore has changed the way it processing genesis file. Instead of reading entire file into RAM it now streams the content. I believe on our side we might not be ready for it and it needs to be checked and fixed if needed.

**Comment by bowenwang1996** [comment]
I am really sorry that I didn't check with you on that. Please sync with @posvyatokum on this.

**Comment by khorolets** [comment]
We haven't seen any problems and had refactored the way we read genesis records on the Indexer for Explorer side some time ago. Closing the issue.
