### ISSUE TITLE
explorer transaction says succeeded when it failed

### ISSUE THREAD

**Issue by evergreen-trading-systems** [near/near-indexer-for-explorer#158]
Explorer does a poor job of communicating failed transactions.

<img width="1490" alt="Screenshot 2021-08-31 at 16 59 25" src="https://user-images.githubusercontent.com/4870868/131536466-3b5461c1-0ae7-4be8-867a-ec59ebf5acae.png">

This is a absolute hellish developer experience. Please fix!

`near-sdk` and `near-cli` all say transactions succeed when they really don't. How do you expect devs to build apps with tools that lie?

This transaction demonstrates the issue https://explorer.testnet.near.org/transactions/A9pRYiQjiMqsnCqj2TsLxPutsJ3KUgPfgLFwi4ZbbnHW

**Comment by frol** [comment]
@evergreen-trading-systems this is the back-end project serving the data for Explorer UI. I have already created a tracking issue for this https://github.com/near/near-explorer/issues/716, so I am closing this one as a duplicate
