### ISSUE TITLE
Indexer can't find transaction but modifies state

### ISSUE THREAD

**Issue by evergreen-trading-systems** [near/near-indexer-for-explorer#159]
I call a smart contract. The smart contract appears to run successfully because it returns the logs showing modified state. 

The transaction-link is empty

https://user-images.githubusercontent.com/4870868/131688709-b825b5fa-661d-4071-8865-6d26bf05cb38.mov

This same command was working 1 hour ago - https://explorer.testnet.near.org/transactions/8U9t49tC99qQP1TCRDxXR8wSmd7edrVhzQRyagZUKvGA

**Comment by frol** [comment]
@evergreen-trading-systems Thanks for reporting it. Indeed our monitoring system did not pick up and alert us. Indexer for Explorer service went down for testnet. We are investigating the issue. /cc @khorolets

**Comment by frol** [comment]
@evergreen-trading-systems Explorer is back online!
