### ISSUE TITLE
Localnet `init`d config isn't runnable due to no tracked shards

### ISSUE THREAD

**Issue by mieubrisse** [near/near-indexer-for-explorer#166]
Config generated with:
```
/usr/local/bin/indexer-explorer --home-dir /root/.near/localnet init --fast --chain-id localnet
```
Requires changing the `"tracked_shards": [],` line in the generated `config.json` to `"tracked_shards": [0],`

**Comment by telezhnaya** [comment]
Hi @mieubrisse 
You are right, it is mentioned in the doc: https://github.com/near/near-indexer-for-explorer#self-hosting

We will support multiple shards at the nearest time, the value could be not only `[0]`, so it's better to leave it as it is. The user should fill it with the desired value.
