### ISSUE TITLE
Create index on field 'method_name' in JSONB args in transaction_actions

### ISSUE THREAD

**Issue by telezhnaya** [near/near-indexer-for-explorer#172]
Also, check whether we should add other indexes on other fields in args

https://github.com/near/near-indexer-for-explorer/discussions/171

**Comment by AngelBlock** [comment]
It will be great to also have an index on 
`receiver_account_id` table `transactions` please.

**Comment by AngelBlock** [comment]
@frol Are you referring to this particular query or what index will be capable of, in general? This query is used for the sputnik DAO v1 which has no cross-contract calls, but I assume index needs to cover any future cases which may be beneficial for Sputnik DAO v2 (or any other smart-contract) and query will be different. I believe @roshkins is working on the v2 stats site, so he can shed some light.

**Comment by AngelBlock** [comment]
@frol Understand, you mean with that query as an example we are not catching the 2FA interactions. Thanks, will raise an issue in the repo to address it. Is there an index on `action_receipt_actions`?

**Comment by frol** [comment]
I believe we don't need that index on transaction tables
