### ISSUE TITLE
IO error: while open a file for lock: ../near/mainnet/data/LOCK: Permission denied

### ISSUE THREAD

**Issue by WuTao18** [near/near-indexer-for-explorer#182]
I tried to run near indexer for explorer as archival node. I downloaded the backup and put it in `data` folder. 
I received the error when I ran the node:
![image](https://user-images.githubusercontent.com/32795326/139522311-ce2a9106-c478-498e-badf-a7d2c734b2da.png)

**Comment by sundafa** [comment]
If you are sure that no other programs are using the database, you can delete this file and run it again.

**Comment by WuTao18** [comment]
> If you are sure that no other programs are using the database, you can delete this file and run it again.

I deleted this file and ran the node again, then I encountered the following questions:
![image](https://user-images.githubusercontent.com/32795326/139634347-9fd9081d-e067-40a6-a4a2-70345eabeeef.png)

**Comment by sundafa** [comment]
Explain that you have already run the same program, you need to find the program and close it.
** *** ** @WuTao18 
You may have run the archive node program, but did not close it
This program and the archive node program cannot run at the same time

**Comment by WuTao18** [comment]
> Explain that you have already run the same program, you need to find the program and close it. ** *** ** @WuTao18 You may have run the archive node program, but did not close it This program and the archive node program cannot run at the same time

I have not run the same program. I tried to restart the machine and then run the node again, there is still the same problem.

**Comment by frol** [comment]
You have your data folder corrupted. Please, download a fresh data folder backup: https://docs.near.org/docs/develop/node/validator/running-a-node#starting-a-node-from-backup
