### ISSUE TITLE
`concurrency` Problems caused by concurrency

### ISSUE THREAD

**Issue by sundafa** [near/near-indexer-for-explorer#184]
When I use the default concurrency value of 100, starting at the block height of 4050,000, it is easy to get stuck in the progress and the speed becomes very slow.
When I change to single-threaded 1, then the block can be analyzed smoothly, and there will be no slowness.

**Comment by sundafa** [comment]
So I suggest to modify the tutorial and set it to 1
Multithreading is only used to test data integrity

**Comment by khorolets** [comment]
Thanks for the report. Yeah, it's suboptimal at the moment to try to run Indexer for Explorer in multi-threading mode. We're trying to figure out how to enable a fair multi-thread. I'd keep this issue as a tracking one.

> So I suggest to modify the tutorial and set it to 1
Feel free to create a PR :)
