### ISSUE TITLE
'--download' isn't support?

### ISSUE THREAD

**Issue by JesseChing** [near/near-indexer-for-explorer#207]
when I type the below command
`$ cargo run --release -- --home-dir ~/.near/testnet init --chain-id testnet --download
`
then show the error message：

> **error: Found argument '--download' which wasn't expected, or isn't valid in this context**

 I review the source code ,and  I can't  then '--download' definition in the code

**Comment by khorolets** [comment]
Sorry for that. We need to update the README

Instead of --download use
--download-genesis --download-config

**Comment by JesseChing** [comment]
Thank you for you response @khorolets
