### ISSUE TITLE
feat: Store index in chunk and block timestamp in transactions and receipts tables for better indexing

### ISSUE THREAD

**Issue by khorolets** [near/near-indexer-for-explorer#21]

**Comment by frol** [comment]
Also, add the `block_timestamp` column, so we can easily order the transactions and count how many transactions were processed in the last 24 hours without a need to do an expensive JOIN.

**Comment by frol** [comment]
We also need to have indices on those columns (`index_in_chunk` and `block_timestamp`)

**Comment by khorolets** [comment]
Closed by #30
