### ISSUE TITLE
Connection Issues to public db

### ISSUE THREAD

**Issue by nvk8sbf** [near/near-indexer-for-explorer#220]
Hi- I've been having trouble connecting to the mainnet db for several days now (postgres://public_readonly:nearprotocol@mainnet.db.explorer.indexer.near.dev/mainnet_explorer). Problem didn't start until this past weekend. Tested from 3 different computers at 3 different locations, getting same error: 

``connection to server at "mainnet.db.explorer.indexer.near.dev" (35.189.204.60), port 5432 failed: Connection timed out (0x0000274C/10060) Is the server running on that host and accepting TCP/IP connections?``

**Comment by AngelBlock** [comment]
The same issue :(
```Error: connect ETIMEDOUT 35.189.204.60:5432
code: 'ETIMEDOUT'
address: '35.189.204.60'
port: 5432
```

**Comment by frol** [comment]
I hope we have patched the issue with our pgbouncer that we use for public access. Please, feel free to re-open this issue if you bump into it again.
