### ISSUE TITLE
Connection Issues to public db (cont.)

### ISSUE THREAD

**Issue by nvk8sbf** [near/near-indexer-for-explorer#222]
Re-opening issue in reference to #220 

Still getting error
`connection to server at "mainnet.db.explorer.indexer.near.dev" (35.189.204.60), port 5432 failed: Connection timed out (0x0000274C/10060) Is the server running on that host and accepting TCP/IP connections?`

db was unreachable around 12/25 to 1/3

query worked 1/7

back down today 1/11

**Comment by khorolets** [comment]
@nvk8sbf I believe some action points were taken in this regard. Could you recheck and let us know, please?
