### ISSUE TITLE
Some transactions are missing on contract page

### ISSUE THREAD

**Issue by poddubnyoleg** [near/near-indexer-for-explorer#232]
## Problem
Sometimes transaction to a contract is not shown on contract page of explorer. In the same time transaction is successfully completed and visible on signer's page.

E.g. tx https://explorer.testnet.near.org/transactions/GSSJMsdNkW2q8VsCqAx3iHQMZe9HcMhYFSeoqf3a8Zx is not visible on contract page https://explorer.testnet.near.org/accounts/swt07.intmainreturn000.testnet

## How did we discover this problem?
Problem occurs when i send multiple transactions to the same contract from different signers. Missed txs are always from the same signers

**Comment by frol** [comment]
@khorolets This is super odd, but indeed, we don't have the transaction in the indexer database. I don't recall us doing anything on Jan 7 that could lead to the data loss.

**Comment by khorolets** [comment]
```
select transaction_hash, receiver_account_id from transactions where transaction_hash = 'GSSJMsdNkW2q8VsCqAx3iHQMZe9HcMhYFSeoqf3a8Zx' and receiver_account_id = 'swt07.intmainreturn000.testnet';
              transaction_hash               |      receiver_account_id
---------------------------------------------+--------------------------------
 GSSJMsdNkW2q8VsCqAx3iHQMZe9HcMhYFSeoqf3a8Zx | swt07.intmainreturn000.testnet
```

The transaction `GSSJMsdNkW2q8VsCqAx3iHQMZe9HcMhYFSeoqf3a8Zx` is present in the database.

Sorry, I couldn't scroll to the transaction on the account page of the Explorer (too many transactions and infinity scroll)

**Comment by frol** [comment]
@khorolets Sorry, my bad, I did not notice it was testnet 🤦 

@poddubnyoleg We cannot reproduce the issue now, but the data is clearly in the database. Please, re-open the issue if you observe it again, we will try to jump on it asap, so we can investigate it.
