### ISSUE TITLE
"Looking for parent transaction hash in database for 1 receipts"

### ISSUE THREAD

**Issue by frol** [near/near-indexer-for-explorer#242]
![image](https://user-images.githubusercontent.com/304265/151039165-8709a103-ad58-47a0-9132-34d858ac7456.png)

After a 10 minutes of indexer running I still see those warnings (we expect to only see them during a few first blocks, btw, we should make the message clear that it is fine to ignore those warnings during the indexer warm-up [or even better if we don't even print those warnings during the warm-up]).

Also, I see an increased number of

```
DatabaseError(ForeignKeyViolation, "insert or update on table \"receipts\" violates foreign key constraint \"tx_receipt_fk\"")
```

**Comment by khorolets** [comment]
@telezhnaya correct me if I'm wrong. But database error is the expected one, those retries you've left intentionally.

**Comment by telezhnaya** [comment]
The cause of error&retry may be here https://github.com/near/near-indexer-for-explorer/blob/master/src/main.rs#L87
But, if it appears more frequently, it means that it may be not the only reason

**Comment by khorolets** [comment]
> The cause of error&retry may be here https://github.com/near/near-indexer-for-explorer/blob/master/src/main.rs#L87 But, if it appears more frequently, it means that it may be not the only reason

Yes, that is the reason. I've experimented and made it sequential again. That had proven the theory. @frol I'm not sure we should worry about it. Anyway, it's a separate "problem".

I'm investigating the "Looking for parent transaction hash..." message.
