### ISSUE TITLE
Inconsistency in block ordinal to block hash mapping found at block height

### ISSUE THREAD

**Issue by sundafa** [near/near-indexer-for-explorer#252]
Version v0.10.10
This error is displayed when running node again after updating the database

```
Inconsistency in block ordinal to block hash mapping found at block height 47443088
Inconsistency in block ordinal to block hash mapping found at block height 47489088
Inconsistency in block ordinal to block hash mapping found at block height 47541952
Inconsistency in block ordinal to block hash mapping found at block height 47627178
```

**Comment by khorolets** [comment]
@sundafa it'd be nice if you provide:

* OS you're using
* chain-id (localnet, testnet, mainnet) you're running
* A little bit more logs to reason about what has been happening before you've started to observe this messages

**Comment by sundafa** [comment]
@khorolets Subsequent observations can continue to synchronize block heights.
OS: Ubuntu 20.04
chain-id: mainnet
The database data is dumped from other servers. After a long time, the archive node is synchronized and the indexer program can run.
Other information is no different from normal operation, And after restarting again today, I did not see the relevant errror message.

**Comment by frol** [comment]
This was nearcore internal storage migration from version 30 to 31. It was expected that those blocks would be fixed automatically, and this message can be safely ignored.
