### ISSUE TITLE
What's the correct way to index from Genesis?

### ISSUE THREAD

**Issue by sarin-dotin** [near/near-indexer-for-explorer#253]
We are running an indexer in archive mode.
```
./indexer-explorer --home-dir /root/.near/testnet run --stream-while-syncing --store-genesis --concurrency 300 --non-strict-mode sync-from-interruption
```
But it's only syncing from the current block.
We tried `sync-from-block --height 42376923`, now it syncs from the first block but when the container restarts it tries to sync again from the start

**Comment by khorolets** [comment]
@sarin-dotin the behavior you've described is correct.

* `sync-from-interruption` will try to find the record your node did during the previous run and will start after the block it indexed last. If this record is missing it will act like `sync-from-latest`
* `sync-from-block --height N` will **always** start from the `N` block
* `sync-from-latest` will query the node to find out which block is the final and will start from it

I see what you're trying to achieve, but it's not possible. The design of the NEAR Indexer for Explorer assumes you're running the node constantly so `sync-from-interruption` is the way to go on a regular basis. 

If your goal is to index data from the genesis to the tip of the network and after that to continue indexing, you need to `sync-from-block ...` manually to the tip of the blockchain and then use `sync-from-interruption`

Feel free to reopen the issue if you have more questions in this regard or open a new one if you have different questions :)
