### ISSUE TITLE
taking too long time to sync mainnet as archival mode

### ISSUE THREAD

**Issue by marcelo-gonzalez** [near/near-indexer-for-explorer#260]
This is reposted from zendesk: https://nearhelp.zendesk.com/agent/tickets/4468

We're running Indexer Explorer in AWS c5.4xlarge (16 CPUs and 32GB memory) in archive mode and we have extracted the 4.9TB data.tar back up from S3 into data folder. We're using Aurora postgres database with 4 CPUs and 16 GB memory. 

We're using --concurrency 50000 sync-from-block --height 9820100. After 5 days, our Postgres DB only grew to 50GB. Have no idea how long it'll take to sync all of the history data (Based on the documentation, the full DB will be around 1.1TB).

I saw very low indexer node CPU load (below 5) and the DB node load is also very low.

Could you please advise any of the optimization or changes to make the sync faster? Could you please advise the related config.json file changes we need to improve the sync performance?

We're using the original config.json file with 2 changes. "archive" = true and "tracked_shards": [0]. The command line we're using to run indexer node is:

./target/release/indexer-explorer --home-dir /indexer/near/mainnet run --store-genesis --stream-while-syncing --non-strict-mode --concurrency 50000 sync-from-block --height 9820100

Thanks for your help,

GB

<img width="1198" alt="indexer-ec2-load" src="https://user-images.githubusercontent.com/37846884/155337357-d0e4dbac-dd6d-43c5-8c11-43ae5334e1cf.png">
<img width="901" alt="db-load" src="https://user-images.githubusercontent.com/37846884/155337368-798e3b11-9484-4be6-bfd7-6f545a7c009b.png">

[config.json.txt](https://github.com/near/near-indexer-for-explorer/files/8124990/config.json.txt)

[LOG.txt](https://github.com/near/near-indexer-for-explorer/files/8124992/LOG.txt)

**Comment by khorolets** [comment]
Since the author has not reached out to us I'm closing the issue.
