### ISSUE TITLE
Some blocks in DB are broken

### ISSUE THREAD

**Issue by telezhnaya** [near/near-indexer-for-explorer#269]
We have an issue in blocks 47317863, 47317864, 47317865 with index_in_chunk column

We have 2 rows 6,7,8, etc here, at one chunk
```sql
select * from receipts join blocks on receipts.included_in_block_hash = blocks.block_hash
where block_height = 47317863
order by receipts.index_in_chunk;
```

I suggest to delete the info for these 3 blocks and write it again.

**Comment by khorolets** [comment]
I believe you've done it already, no?
