### ISSUE TITLE
Storage location of non conforming event logs

### ISSUE THREAD

**Issue by azizaiden** [near/near-indexer-for-explorer#285]
Hello,

I'd like to ask where are event logs from receipt outcomes for non-standard events stored in the DB?

For example: EVENT_JSON:{"standard":"burrow","version":"1.0.0","event":"repay","data:[

 {"account_id":"niemtin.near","amount":"80730114048068486192848022","token_id":"linear-protocol.near"} 

]}

**Comment by khorolets** [comment]
We don't store logs from `ExecutionOutcomes` in the database.

**Comment by azizaiden** [comment]
Is there a way around it? most dapps emit event logs

**Comment by khorolets** [comment]
Indexer Database won't help here. You'd probably need to write your own indexer for that. 

I'd recommend to use NEAR Lake Framework for that. We have a tutorial about the Events, for JS though https://near-indexers.io/tutorials/lake/nft-indexer
