### ISSUE TITLE
Unable to Lookup Accounts for Public Key

### ISSUE THREAD

**Issue by lewis-sqa** [near/near-indexer-for-explorer#288]
As part of the [Wallet Selector](https://github.com/near/wallet-selector) project, we use the Indexer service (via https://api.kitwallet.app/ & https://testnet-api.kitwallet.app/) to lookup public keys from a user's Ledger device to autofill the matching account id(s).

We got a report from a user earlier today that this service is responding with 404 Not Found for valid public keys. Below is an example url:

```
https://testnet-api.kitwallet.app/publicKey/ed25519:8Mr4NPyQKwVRgqTYZHPD6VAQmNSrBXk1Hx2oH9eBUFsE/accounts
```

**Comment by frol** [comment]
I don't know anything about kitwallet. Indexer for Explorer database has the access key indexed just fine:

<img width="1367" alt="image" src="https://user-images.githubusercontent.com/304265/180234316-01466bfd-59d2-4eb2-8f6d-5fc65ac182b8.png">

**Comment by PinkiNice** [comment]
@lewis-sqa Hey there!
Kitwallet recently restricted access only for whitelisted domains (wallet domain).
Have you considered spinning up your own wallet-selector's API for this purpose?
The source code for query located there https://github.com/near/near-contract-helper/blob/master/src/middleware/indexer.js
