### ISSUE TITLE
Blocks before block height 9820214 not available in indexer 

### ISSUE THREAD

**Issue by simibac** [near/near-indexer-for-explorer#291]
If I ask for the earliest block in the public mainnet indexer I get the following result:

![image](https://user-images.githubusercontent.com/15369592/181470329-5de95864-6b8b-4324-b552-16da002bd08d.png)

Is there a specific reason or historical change that blocks (July 21, 2020 at 11:50:10pm) before then are not available?

**Comment by PizBernina** [comment]
having the same issue

**Comment by khorolets** [comment]
Because it is the Genesis block the mainnet has started from. 

There's nothing before that block.
