### ISSUE TITLE
Cargo build --release fails  when running on ubuntu 22

### ISSUE THREAD

**Issue by Madgeniusblink** [near/near-indexer-for-explorer#302]
So I followed the README to set up the indexer.

*   installed rust version 1.63.0
*   ran `sudo apt install libpq-dev`
     -` cargo install diesel_cli --no-default-features --features "postgres"`
     -` diesel migration run`. this command failed with `error applying hunk #1`. I then manually copy-pasted SQL for this in Postgres

All of this worked fine. However, when I'm trying to run `cargo build --release` it gives the following error. Any help would be appreciated. Thank you!

<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/42707764/189141504-58aa4526-859f-4e6a-a90c-f8f88ec103e5.png)</span>
 <span class="image-wrap" style="">![](https://user-images.githubusercontent.com/42707764/189141545-f496b78b-214a-407f-b878-766d69b01058.png)</span>

**Comment by sundafa** [comment]
I have the same problem
Hello, I'm having trouble starting after upgrading near-indexer-for-explorer to version 0.10.23
OS: ubuntu 20.04
postgresql: 14
[err.txt](https://github.com/near/near-indexer-for-explorer/files/9533456/err.txt)

**Comment by sotcsa** [comment]
The same issue described in #299 
I have tried to run cargo build without diesel run -> no issue
But if run first diesel run -> "error applying hunk #1" and after it cargo build fails (because diesel changed that schema.rs)

**Comment by Madgeniusblink** [comment]
Closing this issue as I found a workaround. Check @codedem comment on #299
