### ISSUE TITLE
Can not access to testnet db: postgres://public_readonly:nearprotocol@testnet.db.explorer.indexer.near.dev/testnet_explorer

### ISSUE THREAD

**Issue by hoangphuongcs** [near/near-indexer-for-explorer#315]
Hi, today I can't access the testnet db, can you guys help me? 
FATAL:  remaining connection slots are reserved for non-replication superuser connections
 Many thanks!

**Comment by frol** [comment]
@hoangphuongcs There is not really much we can do about it. The resource is scarce and as it is mentioned in the docs, users should be mindful about their use of it:

> NOTE: Please, keep in mind that the access to the database is shared across everyone in the world, so it is better to make sure you limit the amount of queries and individual queries are efficient.

I recommend you learn more about:
1. Pagoda Alerts: https://console.pagoda.co/alerts
2. Pagoda Enhanced API: https://console.pagoda.co/apis
3. Implementing custom indexers: https://near-indexers.io/docs/projects/near-lake-framework
4. Self-host Indexer for Explorer (I definitely cannot recommend this route as it is a heavy lift)
