### ISSUE TITLE
SQL timeouts for various queries on mainnet DB

### ISSUE THREAD

**Issue by singulart** [near/near-indexer-for-explorer#319]
Example query that fails to return data due to timeout:
```
select count(*) from transactions where block_timestamp > 1666656000;
```

Error message: `canceling statement due to statement timeout`

**Comment by telezhnaya** [comment]
Hey @singulart ,
Public read-only replica has huge load and it's not intended for heavy requests. `count(*)` usually requires sufficient resources.

If you want to find the number of transactions after a specific date, you can use [NEAR Analytics](https://github.com/near/near-analytics) instead.

**Comment by singulart** [comment]
Thanks a lot for your support! I will try near analytics!
