### ISSUE TITLE
Resolve conflicting/duplicating CreateAccount/DeleteAccount actions

### ISSUE THREAD

**Issue by frol** [near/near-indexer-for-explorer#32]
The problem is two-fold:

1. Use the logic we have for access keys to resolve the updates to the same account (getting multiple CreateAccount / DeleteAccount actions in a single chunk we need to squash those changes to a single INSERT or UPDATE query)
2. Come up with the solution to make the updates/inserts idempotent to avoid the situation when two concurrent nodes may rewrite each other changes

My proposed solution is to introduce `last_update_block_height` into `accounts`/`access_keys` tables so we can rely on it, and instead of doing:

```sql
UPDATE access_keys
SET
    deleted_at_receipt_id = 'abcd'
WHERE
    account_id = 'frol.near'
    AND
    public_key = 'ed25519:...'
```

we do

```sql
UPDATE access_keys
SET
    deleted_at_receipt_id = 'abcd',
    last_update_block_height = :current_block_height
WHERE
    account_id = 'frol.near'
    AND
    public_key = 'ed25519:...'
    AND
    block_height < :current_block_height
```

This way it will successfully update the record if the last update was before the current block height, and silently ignore the update if we are behind the latest state in the database.

NOTE: I have not put any thought into the `INSERT ... ON CONFLICT` statements that we need when we create the account, so you will need to design the solution yourself.

**Comment by khorolets** [comment]
Close #34
