### ISSUE TITLE
Are Docker images publicly available?

### ISSUE THREAD

**Issue by klefevre** [near/near-indexer-for-explorer#337]
In the [Deployments](https://github.com/near/near-indexer-for-explorer#deployments) section of the README it is stated that Docker images are built using Google Cloud Build and deployed using Google Cloud Run.

Are these images deployed to be used publicly?

Is yes, can anybody tell me how can we access these artifacts please? If no, well that would be unfortunate as, IMHO, it would be very interesting and valuable to be able to access theses images for people who don't want to deal with compiling and/or managing Docker images manually.

Thanks for the good work!

**Comment by khorolets** [comment]
Hey there!

The information about those images in the README serves a few purposes: 
- a note to the infra team
- as a tip how it can be used

Sorry, those images are not publicly available as it would mean we have to maintain that while we don't have capacity for that. 

I think we can consider publishing Docker images in the future if we have requests for that and enough capacity. 

So far it's the first request 🤔
cc @pkudinov @ecp88

**Comment by klefevre** [comment]
Thank you for clarification. I will then handle this manually. I hope this become a feature in the future.
Bye
