### ISSUE TITLE
near-indexer-for-explorer based on nearcore doesn't work

### ISSUE THREAD

**Issue by WuTao18** [near/near-indexer-for-explorer#348]
I am currently using the old version (2d66461993a867f6611beab6f567593808dedee3) of near-indexer-for-explorer, which uses nearcore instead of near lake framework. The reason I still use the old version of near-indexer-for-explorer is that I need to run an archival node. Recently, I found that nearcore in near-indexer-for-explorer could not synchronize data. Specifically, block data could be downloaded, but could not be added to the database (RocksDB) of archival node. I tried to run a rpc node with nearcore (version 1.31.0), and synchronization is OK. So I tried to update the nearcore version in Cargo.toml of near-indexer-for-explorer, but the compilation failed.

Below is my modified Cargo.toml:
![image](https://user-images.githubusercontent.com/32795326/218089035-3a0387e0-4317-435c-9bef-02450c4a79da.png)

And the output from running `cargo build --release`:
[log.txt](https://github.com/near/near-indexer-for-explorer/files/10707219/log.txt)

**Comment by khorolets** [comment]
Hey there! Sorry for inconveniences, but we don't have capacity to keep supporting the version of the indexer we are not using. 

However, I believe we've got you covered this time. We went through similar issues upgrading the nearcore based indexer recently. 

You may refer to this pull request and it's changes to apply it to the indexer for Explorer https://github.com/near/near-lake-indexer/pull/61

I am encouraging you to send a PR once you succeed with the target branch `master-nearcore` to help others.

**Comment by WuTao18** [comment]
> Do you mean you need to have all the data, including the historical one, to be still available?
> With Lake based indexer, you always have all the data.

As far as I know, the only way to query the state of a contract under a block is through the [RPC API](https://docs.near.org/api/rpc/contracts#view-contract-state), so I run an archival node. The reason I run indexer is because I need to query all transactions of an account, and perform other similar queries, the postgresql database maintained by indexer meets my need. Running indexer based on nearcore, I can get both an archival node and a postgresql database.

**Comment by WuTao18** [comment]
> However, I believe we've got you covered this time. We went through similar issues upgrading the nearcore based indexer recently.
> 
> You may refer to this pull request and it's changes to apply it to the indexer for Explorer [near/near-lake-indexer#61](https://github.com/near/near-lake-indexer/pull/61)
> 
> I am encouraging you to send a PR once you succeed with the target branch `master-nearcore` to help others.

OK, let me try.

**Comment by khorolets** [comment]
Resolved by @WuTao18 with #355. `master-nearcore` branch is up to date with `nearcore` 1.31.1

https://github.com/near/near-indexer-for-explorer/commit/f5317db9db24e55b832c362fa1778dccc6aea991

Thank you @WuTao18!
