### ISSUE TITLE
ILLEGAL Instruction Error

### ISSUE THREAD

**Issue by nabeel99** [near/near-indexer-for-explorer#356]
Hey near-team,
I ran a kurtosis local environment , to setup a local testing environment, I used the near workspaces crate and extended it to connect it to a local node, I was able to do it with some success i.e create local accounts, deploy contracts, but this worked fine for normal nep 141 ft contracts , when I tried initialising my own custom contract , I was met with the error , "RPC Timed out".
To further debug this I tried looking up at the docker container logs for the rpc node and was met with the following errors, 
https://discord.com/channels/490367152054992913/912467453479616542/1077294044687904829,
Apparently after some foreign key errors it prints out "ILLEGAL INSTRUCTION" and crashes, I tried getting a response from the kurtosis team but they advised me to get someone from the near team who is familiar with the near indexer to help debug it as its like a near indexer issue, Hoping to receive any suggestions which could help debug or clear this roadblock.

Kurtosis gh issue : https://github.com/kurtosis-tech/near-package/issues/39

**Comment by khorolets** [comment]
@nabeel99 hey there! I am sorry for the inconvenience the issue you have doesn't seem to be directly related to the indexer as a code base. I've provided details on the Kurtosis issue you mentioned.

Ref: https://github.com/kurtosis-tech/near-package/issues/39#issuecomment-1441390091
