### ISSUE TITLE
Cannot perform queries for public accessed db - mainnet2

### ISSUE THREAD

**Issue by kir-ostapchuk** [near/near-indexer-for-explorer#357]
I successfully connected using pgAdmin and IntelliJ Idea built-in DB viewer to public mainnet DB server. Afrer that I tried to execute a query on mainnet2 db and encountered the error: _ERROR: permission denied for table {table_name}_.

How to solve this issue?

**Comment by telezhnaya** [comment]
Could you please try 
```bash
 psql postgres://public_readonly:nearprotocol@mainnet.db.explorer.indexer.near.dev/mainnet_explorer
```
From your terminal?
It works fine to me
<img width="1309" alt="Screenshot 2023-02-27 at 12 07 59" src="https://user-images.githubusercontent.com/11246099/221508234-8b1dbe0f-c64c-4ebc-8cf4-ce9cdf9697c8.png">

**Comment by kir-ostapchuk** [comment]
Thank you so much @telezhnaya for your help. I got where I was wrong. It works both in pgAdmin and Intellij Idea. No actions needed.
