### ISSUE TITLE
Cannot connect to db - no more connections allowed?

### ISSUE THREAD

**Issue by opqpop** [near/near-indexer-for-explorer#372]
Hi, our db connection to near-indexer-for-explorer used to work, but recently started failing w/ max connections allowed issues. Any suggestions for what we can do?

```
OperationalError('connection to server at "mainnet.db.explorer.indexer.near.dev" (35.189.204.60), port 5432 failed: ERROR:  no more connections allowed (max_client_conn)\n')
```

How we connect (per the README postgres://public_readonly:nearprotocol@mainnet.db.explorer.indexer.near.dev/mainnet_explorer)

```
    db_name = "mainnet_explorer"
    db_host = "mainnet.db.explorer.indexer.near.dev"
    db_user = "public_readonly"
    db_password = "nearprotocol"
    database.init(
        db_name, host=db_host, user=db_user, password=db_password, max_connections=10
    )
    return database
```

**Comment by khorolets** [comment]
Sure, I'd be happy to help! Here's a more polite rephrasing:

Hey @opqpop,

I'm truly sorry to hear that you're facing difficulties accessing the database. Regrettably, we are unable to provide exclusive access as it's shared worldwide, as mentioned in the README. If you rely heavily on this data, I kindly suggest considering hosting the [Indexer for Explorer yourself](https://github.com/near/near-indexer-for-explorer#self-hosting) to ensure uninterrupted access. Please let me know if there's anything else I can assist you with.
