### ISSUE TITLE
Failed to get block heights from bucket near-lake-data-mainnet: AWS S3 error

### ISSUE THREAD

**Issue by mrkriodev** [near/near-indexer-for-explorer#378]
1. Ihave the account on AWS.
2. I've configured my ~/.aws/credentials  and ~/.aws/config
3. fulfill .env correctly 
4. builded indexer-explorer on host runs correctly

but while running form Dockerfile
indexer-explorer --concurrency 1 mainnet from-genesis
I have such error " WARN near_lake_framework: Failed to get block heights from bucket near-lake-data-mainnet: AWS S3 error"

5. folder .aws COPY to docker-image as .env file

I cant understand what the matter of this and how to fix it.

**Comment by khorolets** [comment]
I am sorry, it's hard to tell.

Could you provide the command you run the docker image with?

> folder .aws COPY to docker-image as .env file

You don't need both `.aws/credentials` and credentials in `.env`

Example `.env` file that should be enough:
```
DATABASE_URL=postgresql://user:pass@host/db_name
AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
AWS_DEFAULT_REGION=eu-central-1
```

**Comment by mrkriodev** [comment]
1.command is ENTRYPOINT [ "./indexer-explorer", "mainnet", "from-genesis"]
2. example of your  .env file
> DATABASE_URL=postgresql://user:pass@host/db_name
AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
AWS_DEFAULT_REGION=eu-central-1

a little bit different from official one:
> $ echo "AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE" >> .env
$ echo "AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY" >> .env

and i try to add AWS_DEFAULT_REGION to .env also

**Comment by mrkriodev** [comment]
> and i try to add AWS_DEFAULT_REGION to .env also

Didn't help.
Even export all params before command didn't help

**Comment by khorolets** [comment]
> a little bit different from official one:

My bad, sorry.

You need both `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` with your own id and secret (obviously)
```
DATABASE_URL=postgresql://user:pass@host/db_name
AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE
AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
AWS_DEFAULT_REGION=eu-central-1
```

As I said, it's hard to debug your problem. I can assume something maybe wrong with your credentials.

Try using AWS CLI and copying the `block.json` directly to check your credentials are set up correctly and has all the necessary permissions to use S3

```
aws s3 cp s3://near-lake-data-mainnet/000098795971/block.json ./ --request-payer requester
```

ref: [AWS CLI](https://aws.amazon.com/cli/)

**Comment by mrkriodev** [comment]
I've solved the problem. It was in NAT from virtual machine that i used. AWS client doesn't like NAT )
