### ISSUE TITLE
refactor: Handle ExecutionOutcomes

### ISSUE THREAD

**Issue by khorolets** [near/near-indexer-for-explorer#4]
Since 0.2.x NEAR Indexer Framework we are receiving receipts' execution outcomes separately from transaction ones (see #3 ), so we need to handle `ExecutionOutcomes` properly (separate table and here we should have only outcomes for receipts.

**Comment by khorolets** [comment]
@frol btw don't you think there can be a scenario when we want to query through all execution outcomes, including the transaction ones? Clarifying just in case.

**Comment by frol** [comment]
I cannot think of any use-case that would require that

**Comment by khorolets** [comment]
Closing by #10
