### ISSUE TITLE
More indices and renaming

### ISSUE THREAD

**Issue by frol** [near/near-indexer-for-explorer#41]
The general theme about indices: add indecies to most of the foreign key and compound primary key fields. Without these indecies most of the queries take at least 100ms, and can go as bad as several seconds at the moment.

The field names need to be consistent and help to reason about the relations. Let's take an example: `hash` in a `blocks` table is probably fine, but when we have `block_hash`, `chunk_hash` and `hash` in `transactions` table it is getting nasty, so I suggest we always indicate what hash we store, and it would probably be even more helpful if we name `block_hash` in `transactions` table as `included_in_block_hash`. What do you think? /cc @khorolets @icerove 

`blocks`
* rename `height` -> `block_height`
* rename `hash` -> `block_hash`
* rename `prev_hash` -> `prev_block_hash`
* rename `timestamp` -> `block_timestamp`

`chunks`
* index ~`block_hash`~ (#36)
* rename `hash` -> `chunk_hash`

`transactions`
* index `block_hash` (+ consider `included_in_block_hash` renaming applied to all the relevant use-cases)
* index `chunk_hash` 
* index `signer_account_id`
* index `receiver_account_id`
* index `public_key` (+ rename to `signer_public_key` - double-check it)

`transaction_actions`
* index `transaction_hash`
* rename `index` to `index_in_transaction`

`receipts`
* index `block_hash`
* index `chunk_hash`
* index `predecessor_account_id`
* index `receiver_account_id`

`receipt_data`
* index `receipt_id` (we need to rename it to something meaningful)

`receipt_actions` (meh, I need another go over this naming as I get constantly confused by it :disappointed:)
* consider index `signer_account_id` (I am not sure about its use at the moment)

`receipt_action_actions`
* index `receipt_id`

`receipt_action_output_data`
* index ~`data_id`~ (added in some recent PR)
* index `receipt_id`
* consider index `receiver_account_id` (I am not sure about its use at the moment)

`receipt_action_input_data`
* index `data_id`
* index `receipt_id`

`execution_outcomes`
* index `block_hash`

Please suggest more if you encounter.

**Comment by khorolets** [comment]
Closed by #43
