### ISSUE TITLE
Introduce a CLI option to force syncing blocks when still in "is_syncing" mode

### ISSUE THREAD

**Issue by frol** [near/near-indexer-for-explorer#51]
It is useful for debugging purposes and fast iterations on syncing specific data that does not require full sync.

`--index-without-waiting-for-full-network-sync` (it is a placeholder name :smile:)

NOTE: this will require the option implemented on the nearcore streamer side as well.

**Comment by khorolets** [comment]
@frol How about `--stream-while-syncing`?

**Comment by khorolets** [comment]
Related PR on `nearcore` side https://github.com/near/nearcore/pull/3636

**Comment by frol** [comment]
Sounds good to me! 👍

**Comment by khorolets** [comment]
Closed by #52
