### ISSUE TITLE
[Icebox] Index function call arguments

### ISSUE THREAD

**Issue by frol** [near/near-indexer-for-explorer#54]
Currently, function call arguments are stored in transaction/receipt action args JSONB column in base64 encoding, and thus it is impossible to query those from SQL, since FUNCTION_CALL action has the following structure:

```json
{
  "method_name": "ping",
  "args_base64": "e30="
}
```

We may consider indexing those function calls which use JSON into a separate table to enable querying internal.

Alternatively, we should consider building a special service like TheGraph for custom filters/indexers.

**Comment by khorolets** [comment]
@frol this seems to be addressed in #99
