### ISSUE TITLE
indexer for tracking transfers

### ISSUE THREAD

**Issue by bowenwang1996** [near/near-indexer-for-explorer#8]
Integration partners would like to have an indexer that can track all receipts that contain transfers to a specific set of accounts.

**Comment by khorolets** [comment]
@bowenwang1996 could you give a bit more details how to recognise the receipts that contains transfers, please?

**Comment by bowenwang1996** [comment]
I am still waiting to get more details, but basically they will want some notification system that pushes notification when the balance of one of the accounts they care about changes and they potentially need the corresponding transactions.

**Comment by khorolets** [comment]
@bowenwang1996 I suppose we can close this issue?

**Comment by bowenwang1996** [comment]
yes
