### ISSUE TITLE
Weird balance changes in the moment of VALIDATOR_ACCOUNTS_UPDATE

### ISSUE THREAD

**Issue by telezhnaya** [near/near-indexer-for-explorer#81]
In the moment of reward, liquid amount for `jazza.poolv1.near` raised dramatically, and stake decreased. I can't explain the process behind both of these changes. @bowenwang1996 could you please help?

```
select * from account_changes
where account_changes.changed_in_block_timestamp > 1615775643106397811 AND account_changes.changed_in_block_timestamp < 1615812599676806812 
AND account_changes.affected_account_id = 'jazza.poolv1.near'
order by account_changes.changed_in_block_timestamp;
```

| liquid | stake |
| - | - |
| `203513788946994521008902241` | `3277075738533977555810040143262` |
| `741399745512700845188547240` | `3277075737545599543519640143262` |

**Comment by bowenwang1996** [comment]
This is likely because at the beginning of the epoch their stake is returned to them and therefore the liquid balance increases.

**Comment by frol** [comment]
@telezhnaya I think I know the cause for the liquid balance bumps: when you explicitly do stake, you fix the amount, but on the epoch boundary, you get the rewards, and it seems that those rewards get to your liquid balance since the new staked amount is fixed. What I still find confusing is why the staked amount gets reverted to the value it was on before the ping (re-stake). Please, dump all the data we were looking into and let Bowen give some explanations on how to reason about those changes.

**Comment by telezhnaya** [comment]
The original query contained more rows:
```
select * from account_changes
where account_changes.changed_in_block_timestamp > 1615775641257930020 AND account_changes.changed_in_block_timestamp < 1615924811163485425 
AND account_changes.affected_account_id = 'jazza.poolv1.near'
order by account_changes.changed_in_block_timestamp;
```

Here we can see that staked amount increased a little (line 5) and then it decreased at the moment of reward to previous state.

**Comment by telezhnaya** [comment]
@bowenwang1996 sorry, forgot to attach sql output:

acc|timestamp|reason|nonstaked|staked|
-|-|-|-|-|
jazza.poolv1.near | 1615775641257930021 | RECEIPT_PROCESSING | 203514250704858920608902241 | 3277075737545599543519640143262
jazza.poolv1.near | 1615775642203335863 | RECEIPT_PROCESSING | 203513717440636629708902241 | 3277075738533977555810040143262
jazza.poolv1.near | 1615775642203335863 | RECEIPT_PROCESSING | 203513717440636629708902241 | 3277075738533977555810040143262
jazza.poolv1.near | 1615775643106397811 | ACTION_RECEIPT_GAS_REWARD | 203513743581565343008902241 | 3277075738533977555810040143262
jazza.poolv1.near | 1615775643106397811 | RECEIPT_PROCESSING | 203513717440636629708902241 | 3277075738533977555810040143262
jazza.poolv1.near | 1615775643106397811 | ACTION_RECEIPT_GAS_REWARD | 203513743581565343008902241 | 3277075738533977555810040143262
jazza.poolv1.near | 1615775643106397811 | RECEIPT_PROCESSING | 203513717440636629708902241 | 3277075738533977555810040143262
jazza.poolv1.near | 1615786450913260750 | RECEIPT_PROCESSING | 203513743581565343008902241 | 3277075738533977555810040143262
jazza.poolv1.near | 1615786450913260750 | ACTION_RECEIPT_GAS_REWARD | 203513788946994521008902241 | 3277075738533977555810040143262
jazza.poolv1.near | 1615786450913260750 | RECEIPT_PROCESSING | 203513743581565343008902241 | 3277075738533977555810040143262
jazza.poolv1.near | 1615786450913260750 | ACTION_RECEIPT_GAS_REWARD | 203513788946994521008902241 | 3277075738533977555810040143262
jazza.poolv1.near | 1615812270334002739 | VALIDATOR_ACCOUNTS_UPDATE | 741399745512700845188547240 | 3277075737545599543519640143262

The most interesting is the last column. Staked balance increased a little and then decreased right at the moment of reward.

**Comment by bowenwang1996** [comment]
> What I still find confusing is why the staked amount gets reverted to the value it was on before the ping (re-stake).

@frol https://docs.near.org/docs/validator/delegation#fun-facts

**Comment by frol** [comment]
@bowenwang1996 does the rest of my explanation sound reasonable?

**Comment by bowenwang1996** [comment]
> @bowenwang1996 does the rest of my explanation sound reasonable?

Yes

**Comment by telezhnaya** [comment]
Looks like we answered to all the questions. Some examples are covered here: https://github.com/telezhnaya/docs/blob/master/docs/tokens/balances.md#receiving-the-reward-for-being-validator
