### ISSUE TITLE
Denormalize `action_receipt_actions` table in order to improve common queries performance

### ISSUE THREAD

**Issue by frol** [near/near-indexer-for-explorer#87]
* [x] add columns to `action_receipt_actions` table and enable indices for them:
  * [x] `predecessor_account_id`
  * [x] `receiver_account_id`
  * [x] `included_in_block_timestamp`
  
  The motivation is that JOINing with `receipts` table while doing filtering like `receiver_account_id = ? AND action_kind = ? AND args = ?` is slow. @vgrichina Could you provide a minimal useful query?
  
  Ideally, we want to have cross-table indices, but Postgres does not support that, though Postgres 12 and 13 claim to improve various aspects of index performance, so we may want to try to migrate our Postgres 11 database to Postgres 13 to see if that helps.
* [x] add index on `args->>'method_name'` for `FUNCTION_CALL` actions (conditional index in Postgres)
* [x] try to decode base64-encoded `args->>args_base64` to JSON (replace the original base64 field with `args->>args_json` if parsing succeeds), so ultimately we will either have `args_base64` (e.g. rainbow bridge uses borsh instead of JSON args) or `args_json` (commonly used by NEAR smart contracts)
  * [x] consider adding indices to `args->>'args_json'->>'receiver_id'` and `args->>'args_json'->>'amount'` for FT and NFT

**Comment by telezhnaya** [comment]
It is also useful to have `block_height` near `block_hash` column in all places where applicable (we have `block_hash` almost everywhere).
It is easier to understand height (compare to timestamp which is unreadable).
I do not insist on it, though.
