### ISSUE TITLE
`accounts.last_update_block_height` does not show corresponding data

### ISSUE THREAD

**Issue by telezhnaya** [near/near-indexer-for-explorer#91]
Just checked on the data:
`accounts.last_update_block_height` is equal to `accounts.deleted_by_receipt_id` if the account was deleted; otherwise, it is equal to `accounts.created_by_receipt_id`.
Intuitively, I was waiting for the block height with the last update on this account. By the way, I am not sure we need this info since it will produce many updates in DB.

I suggest to get rid of this column and add columns `created_at_block_height` and `deleted_at_block_height`.
We have to make 4 joins to find this info right now 😢

**Comment by frol** [comment]
Oh, sorry for the confusing name. This field is important for another reason. It ensures that when we run two or more indexers from different checkpoints, they don't blindly override data from one another. This is an anchor for concurrent:

```sql
UPDATE accounts SET created_by_receipt_id = 'zxc' WHERE last_update_block_height < :current_block_height
```

```sql
UPDATE accounts SET deleted_by_receipt_id = 'zxc' WHERE last_update_block_height < :current_block_height
```
