### ISSUE TITLE
Document where to find binary releases

### ISSUE THREAD

**Issue by frol** [near/near-indexer-for-explorer#95]

**Comment by khorolets** [comment]
I'll leave it here for a future reference 

`https://s3-us-west-1.amazonaws.com/build.nearprotocol.com/near-indexer-for-explorer/Linux/<branch>/<commit>/indexer`

**Comment by chefsale** [comment]
Added documentation in notion here: https://www.notion.so/nearprotocol/Indexer-Releases-ab1d24c10e8a4510ae8a5b8ee0fa4842. Closing for now.
